language: node_js
node_js:
  - "node"

sudo: required

addons:
    chrome: stable

script: npm run test

before_script:
    - npm install
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
